export const programDetailDictionary = {
  letterOfRec: 'Letters of Recommendation',
  numberOfLetterOfRec: 'Numbers of L.O.R.',
  letterOfRecDetails: 'L.O.R. Details',
  comlexLevelOneAccepted: 'COMLEX LVL 1?',
  comlexLevelOneMininumScore: 'COMLEX LVL 1 Min.',
};

export const programDetailMap = new Map([
  ['programCode', 'Program Code:'],
  ['year', 'For Year:'],
  ['letterOfRec', 'Letters of Recommendation'],
  ['numberOfLetterOfRec', 'L.O.R. Amount?'],
  ['letterOfRecDetails', 'L.O.R. Details'],
  ['comlexLevelOneAccepted', 'COMLEX 1?'],
  ['comlexLevelOneMininumScore', 'COMLEX 1 Min.'],
  ['comlexLevelOneAverageScore', 'COMLEX 1 Avg.'],
  ['comlexLevelOneComments', 'COMLEX 1 Comments:'],
  ['comlexLevelTwoAccepted', 'COMLEX 2?'],
  ['comlexLevelTwoMininumScore', 'COMLEX 2 Min.'],
  ['comlexLevelTwoAverageScore', 'COMLEX 2 Avg.'],
  ['comlexLevelTwoComments', 'COMLEX 2 Comments:'],
  ['usmleLevelOneAccepted', 'USMLE 1?'],
  ['usmleLevelOneMininumScore', 'USMLE 1 Min.'],
  ['usmleLevelOneAverageScore', 'USMLE 2 Avg.'],
  ['usmleLevelOneComments', 'USMLE 1 Comments:'],
  ['usmleLevelTwoAccepted', 'USMLE 2?'],
  ['usmleLevelTwoMininumScore', 'USMLE 2 Min.'],
  ['usmleLevelTwoAverageScore', 'USMLE 2 Avg.'],
  ['usmleLevelTwoComments', 'USMLE 2 Comments:'],
  ['photo', 'Photo?'],
  ['cv', 'CV?'],
  ['deansLetter', "Dean's Letter?"],
  ['transcript', 'Transcript?'],
  ['transcriptComments', 'Transcript Comments:'],
  ['personalStatement', 'Personal Statement?'],
  ['personalStatementComments', 'P.S. Comments:'],
  ['research', 'Research?'],
  ['researchComments', 'Research Comments:'],
  ['auditionRotation', 'Audition Rotation?'],
  ['auditionRotationComments', 'A.R. Comments:'],
  ['doFriendly', 'D.O. Friendly?'],
  ['doFriendlyComments', 'D.O. Comments'],
  ['imsFriendly', 'I.M.G. Friendly?'],
  ['imsFriendlyComments', 'I.M.G. Comments:'],
  ['erasApplication', 'Apply through ERAS?'],
  ['erasApplicationComments', 'ERAS Comments:'],
  ['erasApplicationDate', 'ERAS Date:'],
  ['numberOfApplicationsAccepted', 'Available Spots:'],
  ['otherCommentsOne', 'Comment #1:'],
  ['otherCommentsTwo', 'Comment #2:'],
  ['otherCommentsThree', 'Comment #3:'],
  ['otherCommentsFour', 'Comment #4:'],
  ['otherCommentsFive', 'Comment #5:'],
]);
